#!/bin/bash

runcode()
{
	: '
        Args:        
	    	$1 part file
	    	$2 method
	    	$3 learning rate
	    	$4 num_iterations
	    	$5 batch_size
	    	$6 train data
	    	$7 vocab_file
	    	$8 test data
	    	$9 output file
    '
	python3 $1 $2 $3 $4 $5 $6 $7 $8 $9
}

main()
{
    main_dir=`pwd`
    # Run Q1
	runcode  part_$1_$2.py $2 $3 $4 $5 $6 $7 $8 $9
}

main $1 $2 $3 $4 $5 $6 $7 $8 $9